### ISSUE TITLE
Pixel fallback added for rem units.

### ISSUE THREAD

**Issue by mturnwall** [firstandthird/clientkit#7]
This is the input.

``` css
.btn {
  display: inline-block;
  line-height: 1;
  text-align: center;
  font-size: 0.875rem;
  padding: 0.75rem 0.875rem;
  border: 1px solid transparent;
  border-radius: 3px;
  vertical-align: middle;
}
```

And here is the output

``` css
.btn {
  display: inline-block;
  line-height: 1;
  text-align: center;
  font-size: 14px;
  font-size: 0.875rem;
  padding: 12px 14px;
  padding: 0.75rem 0.875rem;
  border: 1px solid transparent;
  border-radius: 3px;
}
```

A pixel version of rem is being added. All modern browsers support the rem unit and IE has supported it since IE9. I don't think we need a pixel fallback.
